# Generated by Django 4.0.4 on 2022-04-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0012_doctors_patients_delete_doctor_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='created_at',
        ),
    ]
